name: Install dependencies and run tests
description: "A composite action that runs a sequence of steps"
inputs:
  env:
    description: "env to run tests"
    required: false
  some:
    description: "A list of steps to run"
    required: false
  value:
    description: "The working directory"
    required: false
  aws-access-key-id:
    description: ""
    required: false
  aws-secret-access-key:
    description: ""
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "npm"

    - name: List the state of node modules
      continue-on-error: true
      run: npm list
      shell: bash

    - name: Install dependencies
      run: npm install
      shell: bash

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      shell: bash

    - name: Run Playwright tests
      run: npx playwright test
      shell: bash
