name: Install dependencies and run tests
description: "A composite action that runs a sequence of steps"
runs:
  using: "composite"
  steps:
    - run: echo "Step 1"
      shell: bash
    - run: echo "Step 2"
      shell: bash
