name: Playwright tests run manually

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run the tests in"
        type: string
      type:
        description: "text"
        type: string

jobs:  
  reusable_tests_job:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment}}
    steps:
    - uses: actions/checkout@v4

    - name: prepare text
      id: typetext
      run: |
        TYPE=${{ github.event.inputs.type }}
        echo "TYPE=${TYPE}" >> "$GITHUB_OUTPUT"
        ENV=${{ github.event.inputs.environment}}
        echo "TYPE=${TYPE}" >> "$GITHUB_OUTPUT"
    
    - name: override text
      run: |
        TYPE="xxxx"

    - name: get aws secret
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        secret-ids: |
          ENV, arn:aws:secretsmanager:eu-north-1:149536461429:secret:test/beta/acc-crsGQ2


    - name: run tests
      run: |
        echo "Type: $TYPE"
      
    - name: start
      uses: ./.github/actions/run-tests/
      with:
        env: ${{ secrets.ENV_SECRET }}
        some: "some123"
        value: "value123"

    # - name: delete something
    #   run: |
    #     echo "Deleting something"
    #     rm -rf ./featureMap/file-to-delete.yml

    # - name: commit change
    #   run: |
    #    echo "Committing change"
    #    git config --global user.email "karwatmateusz07@gmail.com"
    #    git config --global user.name "karwatmateusz"
    #    git checkout test-b
    #    git add .
    #    git commit -m "test commit"
    #    git push