name: Playwright tests run manually

on:
  workflow_dispatch:
    inputs:
      type:
        description: "text"
        type: string

jobs:  
  reusable_tests_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: prepare text
      id: typetext
      run: |
        TYPE=${{ github.event.inputs.type }}
        echo "TYPE=${TYPE}" >> "$GITHUB_OUTPUT"
    
    - name: override text
      run: |
        TYPE="xxxx"

    - name: run tests
      run: |
        echo "Type: $TYPE"
      
    - name: start
      uses: ./.github/actions/run-tests/
      with:
        some: "some123"
        value: "value123"

    - name: delete something
      run: |
        echo "Deleting something"
        rm -rf ./featureMap/file-to-delete.yml

    - name: commit change
      run: |
       echo "Committing change"
       git checkout test-b
       git add .
       git commit -m "test commit"
       git push