run-name: Action ${{ inputs.environment}} ${{ inputs.type }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run the tests in"
        type: string
      type:
        description: "text"
        type: boolean
      application:
        description: "The application to run tests"
        type: string
permissions:
  id-token: write
  pages: write

jobs:
  reusable_tests_job:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment}}
    steps:
      - name: actor
        run: |
          actor=${{ github.actor }}
          trigger=${{ github.triggering_actor}}
          echo "ACTOR=${actor}" >> "$GITHUB_OUTPUT"
          echo "TRIGGER=${trigger}" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v4
      - name: list files
        run: ls -la

      - name: prepare text
        id: typetext
        run: |
          TYPE=${{ github.event.inputs.type }}
          echo "TYPE=${TYPE}" >> "$GITHUB_OUTPUT"
          ENV=${{ github.event.inputs.environment}}
          echo "TYPE=${TYPE}" >> "$GITHUB_OUTPUT"
          envvar=${{ inputs.type}}
          echo "ENVVAR=${envvar}" >> "$GITHUB_OUTPUT"

      - name: start
        uses: ./.github/actions/run-tests/
        with:
          env: ${{ secrets.ENV_SECRET }}
          application: ${{ inputs.application}}
          some: "ASD"
          value: "value123"
          type: ${{ inputs.type }}
          envvar: ${{ inputs.type }}

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: playwright-report/
  report:
    needs: reusable_tests_job
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: list files
        run: ls -la

      - uses: actions/download-artifact@v4
        with:
          name: test-results
          path: playwright-report/
      - name: list files
        run: ls -la
      - name: setup pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: report
          path: playwright-report/
      - name: list files
        run: ls -la

      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: report
  # - name: delete something
  #   run: |
  #     echo "Deleting something"
  #     rm -rf ./featureMap/file-to-delete.yml

  # - name: commit change
  #   run: |
  #    echo "Committing change"
  #    git config --global user.email "karwatmateusz07@gmail.com"
  #    git config --global user.name "karwatmateusz"
  #    git checkout test-b
  #    git add .
  #    git commit -m "test commit"
  #    git push
