name: Playwright tests run manually

on:
  workflow_dispatch

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: start
        uses: ./.github/actions/run-tests