name: Test workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, reopened]

jobs:
  tests:
    uses: ./.github/workflows/install-run-dependencies.yml
