name: Reusable Test Workflow
on:
  workflow_call:
    inputs:
      caller-repo:
        required: true
        type: string
      pr-number:
        required: true
        type: number
    secrets:
      PAT_TOKEN:
        required: true
  workflow_dispatch:
    inputs:
      caller-repo:
        required: false
        type: string
      pr-number:
        required: false
        type: number

permissions:
  issues: write
  pull-requests: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v4
        # if: ${{ github.event_name == 'workflow_call' }}
        with:
          repository: karwatmateusz/Playwright-template
          token: ${{ secrets.PAT_TOKEN }}

      # - uses: actions/checkout@v4
      # if: ${{ github.event_name == 'workflow_dispatch' }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Set up environment variables
        run: |
          echo "ENVSEC=${{ secrets.ENVSEC }}" >> $GITHUB_ENV
          echo "ENV_SECRET=${{ secrets.ENV_SECRET }}" >> $GITHUB_ENV

      - name: view the secrets context
        shell: bash
        run: echo "$SECRETS_CONTEXT"
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Run tests
        run: npx playwright test

      # - name: Create comment with results
      #   if: always()
      #   uses: peter-evans/create-or-update-comment@v3
      #   with:
      #     repository: ${{ inputs.caller-repo }}
      #     issue-number: ${{ inputs.pr-number }}
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     body: |
      #       Template repository test results for PR #${{ inputs.pr-number }}:
      #       Status: ${{ job.status }}
      #       Run URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
